apiVersion: v1
kind: Namespace
metadata:
  name: database
---
apiVersion: v1
kind: Pod
metadata:
  name: mariadb-deployment
  namepsace: database
  labels:
    app: mariadb
    type: database
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mariadb
        type: database
    spec:
      containers:
        - name: mariadb
          image: mariadb
          ports:
            - containerPort: 3306
              name: db-port
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: my-password
---